services:
    node:
        init: true
        build: .
        command: 
          - bash
          - -c
          - |
            if [ -f package-lock.json ]; then
                npm ci
            else
                npm install
            fi \
              && npm run serve
        volumes:
            - ./:/app
        working_dir: /app
        user: ${UID:-1000}:${GID:-1000}
        ports:
            - ${PORT:-8080}:8080
